security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_SERVER:auth-service}:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGODB_ACCOUNT_SERVER:account-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_ACCOUNT_PORT:27017}

server:
  servlet:
    context-path: /accounts
  port: 6321

feign:
  hystrix:
    enabled: true