
eureka:
  instance:
    health-check-url-path: /actuator/health
    statusPageUrlPath: /actuator/info

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG