logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 10    
    metadata-map:
      management.context-path: ${management.context-path}

  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER:registry}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${AUTH_SERVER:auth-service}:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq

management:
  security:
    enabled: false 
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
    