spring:
  data:
    mongodb:
      host: ${MONGODB_AUTH_SERVER:auth-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_AUTH_PORT:27017}
  boot:
    admin:
      client:
          management-url: /uaa/actuator

eureka:
  instance:
    health-check-url-path: /uaa/actuator/health
    statusPageUrlPath: /uaa/actuator/info
    
  

server:
  servlet:
    context-path: /uaa
  port: 5000

management:
  context-path: /uaa