spring:
  data:
    mongodb:
      host: ${MONGODB_AUTH_SERVER:auth-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_AUTH_PORT:27017}

server:
  servlet:
    context-path: /uaa
  port: 5000
